<style>
    @import url('//<?= URL_VENDOR_FRONTEND ?>/summernote/summernote-dist/summernote.css');
    @import url('includes/css/admin.css');
</style>
<div class="container">
    
    <div class="row">
        <div class="col-md-8">
            <h3 class="admin-page-title"><i class="fa fa-bar-chart-o"></i> Reports</h3>
        </div>
        <div class="col-md-2">
            <a data-toggle="modal" href="#admin-add-modal" data-action="add-report" class="btn btn-info btn-block admin-add-button"><i class="fa fa-bar-chart-o"></i> Generate report</a>        
        </div>
        <div class="col-md-2">
            <a data-toggle="modal" href="#admin-add-template-modal" data-action="add-template" class="btn btn-info btn-block admin-add-button"><i class="fa fa-plus"></i> Add a template</a>        
        </div>
    </div>
    
    <div class="row">
        
        <div class="col-md-12">
        
            <h4>Reports generated</h4>
            
            <table id="admin-reports-generated" class="table table-hover">           
                <thead>
                    <tr>
                        <th scope='col'>Report</th>
                        <th scope='col'>Template used</th>
                        <th scope='col'>Generated by</th>
                        <th scope='col'>Generated on</th>
                        <th scope='col' style='width: 20%;'></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php
                        if (empty($reportsGenerated)){
                            echo "<tr><td colspan='5' class='empty-table-placeholder'>No reports have been generated at this point…</td></tr>";
                        } else {
                            foreach($reportsGenerated as $r) {
                                echo "<tr data-focus='report-{$antiXSS->escape($r['report_id'], $antiXSS::HTML_ATTR)}'
                                          data-report-id='{$antiXSS->escape($r['report_id'], $antiXSS::HTML_ATTR)}'>" .
                                     "<td>" . $r['report_name'] . "</td>" .
                                     "<td>" . $r['template_name'] . "</td>" .
                                     "<td>" . $r['emp_name'] . "</td>" .
                                     "<td>" . $dateFmt->format($r['inserted_on'], 'date_time') . "</td>" .
                                     '<td class="table-option-cell">
                                         <a class="btn btn-info" href="reports.php?page=view-generated-report&report_id=' . $antiXSS->escape($r['report_id'], $antiXSS::HTML_ATTR) . '"><i class="fa fa-eye"></i> View</a>
                                         <button type="button" class="btn btn-danger" data-action="delete"><i class="fa fa-minus"></i> Delete</button>
                                      </td>' .
                                     '</tr>';
                            }
                        }
                        ?>
                    </tr>
                </tbody>
            </table>
        
        </div>
        
    </div>
    
    <div class="row">
        
        <div class="col-md-12">
        
            <h4>Report templates</h4>
            
            <table id="admin-report-templates" class="table table-hover">           
                <thead>
                    <tr>
                        <th scope='col'>Name</th>
                        <th scope='col'>Description</th>
                        <th scope='col'>Created by</th>
                        <th scope='col'>Created on</th>
                        <th scope='col' style='width: 20%;'></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php
                        if (empty($reportTemplates)){
                            echo "<tr><td colspan='5' class='empty-table-placeholder'>No report templates to be shown at this point…</td></tr>";
                        } else {
                            foreach($reportTemplates as $r) {
                                echo "<tr data-focus='template-{$antiXSS->escape($r['template_id'], $antiXSS::HTML_ATTR)}'
                                          data-template-id='{$antiXSS->escape($r['template_id'], $antiXSS::HTML_ATTR)}'
                                          data-template-content='{$antiXSS->escape($r['content'], $antiXSS::HTML_ATTR)}'>" .
                                     "<td>" . $r['name'] . "</td>" .
                                     "<td>" . $r['description'] . "</td>" .
                                     "<td>" . $r['emp_name'] . "</td>" .
                                     "<td>" . $dateFmt->format($r['inserted_on'], 'date_time') . "</td>" .
                                     '<td class="table-option-cell">
                                          <button type="button" class="btn btn-info" data-toggle="modal" href="#admin-add-template-modal" data-action="view"><i class="fa fa-eye"></i> View</button>
                                          <button type="button" class="btn btn-danger" data-action="delete"><i class="fa fa-minus"></i> Delete</button>
                                      </td>' .
                                     '</tr>';
                            }
                        }
                        ?>
                    </tr>
                </tbody>
            </table>
        
        </div>
        
    </div>
    
</div>

<div class="modal fade" id="admin-add-modal" tabindex="-1" role="dialog" aria-labelledby="admin-add-modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-vertical-center">
        <form method="POST" action="reports.php?page=generate-new-report" class="modal-content">
            
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Generate a new report</h4>
            </div>
            
            <div class="modal-body">
            
                <?php
                if (empty($reportTemplates)){
                ?>
                
                <p>A report cannot be generated at this time because there are no templates…</p>
                
                <?php
                } else {
                ?>
                
                <div class="form-group">
                    <label class="control-label" for="template_id">Select the template you'd like to use</label>
                    <select class="form-control" id="template_id" name="template_id" required>
                        <option value="">Pick a template…</option>
                        <?php
                        foreach($reportTemplates as $r) {
                            echo '<option value="' . $antiXSS->escape($r['template_id'], $antiXSS::HTML_ATTR) . '">' . $antiXSS->escape($r['name']) . '</option>';
                        }
                        ?>
                    </select>
                </div>
                
                <div class="form-group">
                    <label class="control-label" for="report_name">Give this report a name</label>
                    <input type="text" class="form-control" id="report_name" name='report_name' required>
                </div>
                
                <?php } ?>

            </div>
                
            <div class="modal-footer">
                <?php
                if (!empty($reportTemplates)){
                    echo '<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Confirm</button>';
                }
                else{
                    echo '<button type="button" class="btn btn-info pull-left" id="redirect-add-template"><i class="fa fa-plus"></i> Add a template</button>';
                }
                ?>
            </div>
            
        </form>
    </div>
</div>

<div class="modal fade" id="admin-add-template-modal" tabindex="-1" role="dialog" aria-labelledby="admin-add-template-modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-vertical-center modal-wide">
        <form id="admin-form-add-template" action='reports.php?page=add-template' method='POST' class="modal-content">
            
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            
            <div class="modal-body">
                
                <div class="form-group group-add-template">
                    <label class="control-label" for="email_subject">Name</label>
                    <input type="text" class="form-control" id="template_name" name='name'>
                </div>
                
                <div class="form-group group-add-template">
                    <label class="control-label" for="email_cc">Description</label>
                    <input type="text" class="form-control" id="template_description" name='description'>
                </div>
                
                <div class="form-group">
                    <label class="control-label" for="email_content">Template content</label>
                    <textarea class="form-control summernote" id="template_content" name='content'></textarea>
                </div>
                
            </div>
                
            <div class="modal-footer">
                <button type="submit" class="btn btn-success group-add-template"><i class="fa fa-check"></i> Confirm</button>
            </div>
            
        </div>
    </div>
</div>
<script src='//<?= URL_VENDOR_FRONTEND ?>/summernote/summernote-dist/summernote.min.js'></script>
<script charset='utf-8' src='includes/js/reports.js'></script>
<script>
    'use strict';
    var focus = '<?= $antiXSS->escape($_GET['focus'], $antiXSS::JS) ?>';

    //Init rich text editor
    $('.summernote').summernote({
        height: '300',
        tabsize: 3
    });
</script>